---
- hosts: all
  sudo: true
  gather_facts: true
  
  tasks:
    - name: enabled mod_rewrite
      apache2_module: name=rewrite state=present
      notify:
        - restart apache2

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted